/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.BmiHistory;
import jooq.tables.records.BmiHistoryRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BmiHistoryRecord> BMI_HISTORY__BMI_PK = Internal.createUniqueKey(BmiHistory.BMI_HISTORY, DSL.name("bmi_pk"), new TableField[] { BmiHistory.BMI_HISTORY.ID }, true);
}
