/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.BmiHistory;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>bmi_history</code>.
     */
    public static final BmiHistory BMI_HISTORY = BmiHistory.BMI_HISTORY;
}
