/*
 * This file is generated by jOOQ.
 */
package com.example.repository.jooq.tables.records;


import com.example.repository.jooq.tables.BmiHistory;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BmiHistoryRecord extends UpdatableRecordImpl<BmiHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bmi_history.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bmi_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bmi_history.height_meter</code>.
     */
    public void setHeightMeter(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>bmi_history.height_meter</code>.
     */
    public Double getHeightMeter() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>bmi_history.weight_kg</code>.
     */
    public void setWeightKg(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>bmi_history.weight_kg</code>.
     */
    public Double getWeightKg() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>bmi_history.date</code>.
     */
    public void setDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>bmi_history.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BmiHistoryRecord
     */
    public BmiHistoryRecord() {
        super(BmiHistory.BMI_HISTORY);
    }

    /**
     * Create a detached, initialised BmiHistoryRecord
     */
    public BmiHistoryRecord(Integer id, Double heightMeter, Double weightKg, LocalDate date) {
        super(BmiHistory.BMI_HISTORY);

        setId(id);
        setHeightMeter(heightMeter);
        setWeightKg(weightKg);
        setDate(date);
        resetTouchedOnNotNull();
    }
}
